port: 8080
logLevel: info
persistence:
  database:
    driver: sqlite3
    connectionString: file:./mount/database/video-to-podcast-service.db
  cookies:
    enabled: true
    cookiePath: ./mount/cookies/youtube-cookies.txt
  media:
    mediaPath: ./mount/resources/media
    tempPath: ./tmp
    allowPartialDownloads: true
