apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "video-to-podcast-service.fullname" . }}-config
  labels:
    {{- include "video-to-podcast-service.labels" . | nindent 4 }}
data:
  config.yaml: |
    port: {{ .Values.service.targetPort | default .Values.service.port }}
    logLevel: {{ .Values.logLevel }}
    persistence:
      database:
        driver: {{ .Values.database.driver }}
        connectionString: {{ .Values.database.connectionString }}
      cookies:
        enabled: {{ .Values.cookies.enabled }}
        cookiePath: {{ .Values.cookies.cookiePath }}
      media:
        mediaPath: {{ .Values.media.mediaPath }}
        tempPath: {{ .Values.media.tempPath }}
