{{- if and .Values.cookies.enabled .Values.cookies.cookieContent (not .Values.cookies.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "video-to-podcast-service.fullname" . }}-cookies
  labels:
    {{- include "video-to-podcast-service.labels" . | nindent 4 }}
type: Opaque
data:
  youtube-cookies.txt: {{ .Values.cookies.cookieContent }}
{{- end }}
